### ISSUE TITLE
Is the viewer example outdated?

### ISSUE THREAD

**Issue by GabrielCNoble** [ufbx/ufbx#101]
I was looking at the example viewer code to try to figure out how to load animations and I noticed that some things don't seem to quite match the current version in the library.

On viewer.c : 530
```
ufbx_transform transform = ufbx_evaluate_transform(stack->anim, node, time);
```
``ufbx_evaluate_transform`` expects a ```ufbx_anim*```, and the way it's being used here suggests that ```ufbx_anim_stack``` at some point held a ```ufbx_anim*```, but currently it seems to contain just a ```ufbx_anim```. There are a few other places where this happens, and a few other structs I also think used to hold a ```ufbx_anim*```.

**Comment by GabrielCNoble** [comment]
Sorry, never mind. I thought I had cloned the library recently, but it was back in December. The (actual) current version has pointers where I was expecting them. Sorry for the noise and keep up the excellent work.

**Comment by bqqbarbhg** [comment]
Fortunately it is compiled and run on CI, so it cannot become _that_ outdated.

However, I'm not very happy at its current state, it's a bit messy and could for example use `ufbx_bake_animation()` to simplfiy it quite a bit. I'd like to at least partially rewrite it but never had the time. On a similar note, there's documentation at https://ufbx.github.io/ but it's not currently advertised as it's heavily in progress as well..

**Comment by GabrielCNoble** [comment]
Thanks for the link. Those docs are looking pretty good and already helped me a lot in fixing what broke after I updated ufbx.
