### ISSUE TITLE
add texture

### ISSUE THREAD

**Issue by leonjpzkennedy** [ufbx/ufbx#143]
hellow, I want to add textures to fbx model, I referenced the Sokol souce code like this
sg_init_image(binds.vs_images[SLOT_blend_shapes], &(sg_image_desc){
			.width = img_width,
				.height = img_height,
				.pixel_format = SG_PIXELFORMAT_RGBA8,
				.data.subimage[0][0] = {
				.ptr = pixels,
				.size=(size_t)(img_width * img_height*4),
			}
		});
The code in file viewer.c,  but it doesn't work

**Comment by bqqbarbhg** [comment]
Heya, I do plan on adding some better viewer examples (including ones with textures) in the future.

This is not really an ufbx issue though so I can't help much, but you can for example look at these to get started:

- Sokol texturing sample: https://github.com/floooh/sokol-samples/blob/master/d3d11/texcube-d3d11.c
- stb_image: https://github.com/nothings/stb/blob/master/stb_image.h
