### ISSUE TITLE
Add support for detecting mesh winding

### ISSUE THREAD

**Issue by tehKaiN** [ufbx/ufbx#145]
Hi,

I'm having a little problem with determining winding in my imported models. I guess that's something that could be winged with custom code, but quick searches yielded info that [There is no way to automatically infer the winding order of a 3D mesh that will work for every possible input.](https://gamedev.stackexchange.com/questions/159379/getting-the-winding-order-of-a-mesh).

Official Autodesk forums [show](https://forums.autodesk.com/t5/fbx-forum/how-to-figure-out-if-the-indices-are-stored-cw-or-ccw/td-p/4141843) that there's `bool FbxMesh::CheckIfVertexNormalsCCW()`. Would it be possible to have something similar in ufbx? Or does FBX not store such info and it's determined in runtime with some math magic?

**Comment by bqqbarbhg** [comment]
Heya!

Winding order should be consistent in nearly all FBX files I've seen, but sometimes you can't trust the source data. According to the documentation of `CheckIfVertexNormalsCWC()`: "Compares the normals calculated by doing cross-products between the polygon vertex and by the ones stored in the normal array."

This sounds like the method mentioned in the StackExchange link above. ufbx doesn't have a direct utility for this, but you can either triangulate the mesh and compare the triangle normals, or use `ufbx_get_weighted_face_normal()` and compare the face normal to the individual vertex normals, something like (untested example, just for illustration):

```c
ufbx_real vec3_dot(ufbx_vec3 a, ufbx_vec3 b) { return a.x*b.x + a.y*b.y + a.z*b.z; }

for (size_t face_ix = 0; face_ix < mesh->faces.count; face_ix++) {
    ufbx_face face = mesh->faces.data[i];
    size_t num_backwards = 0;

    ufbx_vec3 face_normal = ufbx_get_weighted_face_normal(&mesh->vertex_position, face);
    for (size_t i = 0; i < face.num_indices; i++) {
        ufbx_vec3 vertex_normal = ufbx_get_vertex_vec3(&mesh->vertex_normal, face.index_begin + i);
        ufbx_real dot = vec3_dot(face_normal, vertex_normal);
        if (dot < 0.0f) {
            num_backwards++;
        }
    }

    if (num_backwards >= face.num_indices / 2) {
        // Half or more vertices point inside the mesh, flip the face or do something else??
    }
}
```

But like I said, I haven't really run into any FBX files where this would be required, so I'm not planning to add utility to do this within ufbx unless it's an issue that seems to be relatively common.

**Comment by tehKaiN** [comment]
Thanks for reply! Since there's no extra info in fbx and the only solution is doing such computations, that will have to do, I guess.
