### ISSUE TITLE
Baked animation transform

### ISSUE THREAD

**Issue by Vincent-P** [ufbx/ufbx#146]
Hi,
I am trying to improve the animation import pipeline at work by replacing the fbx sdk with ufbx :)

I am not sure why, but our old importer imports a world transform for the root bone: `EvaluateGlobalTransform` for the root bone, and `EvaluateLocalTranslation/Rotation/Scaling` per bone.

So the baked anim keys are the same for regular bones, but for the root bone they don't match the old importer. What would be the equivalent of `EvaluateGlobalTransform` ?

I tried something like this without success:
```cpp
if (bIsRootBone)
{
	double const fInterval = 1.0f / double(uFramerate);
	uint16_t uFrame = 0;
	for (double fTime = 0.0; fTime <= pBakedAnim->playback_duration; fTime += fInterval)
	{
		ufbx_transform oParentFromNodeXform = ufbx_evaluate_transform(pAnimStack->anim, pNode, fTime);
		ufbx_matrix oParentFromNode = ufbx_transform_to_matrix(&oParentFromNodeXform);
		ufbx_matrix oWorldFromParent = pNode->parent->node_to_world;

		ufbx_matrix oWorldFromNode = ufbx_matrix_mul(&oWorldFromParent, &oParentFromNode);
		ufbx_transform oWorldFromNodeXform = ufbx_matrix_to_transform(&oWorldFromNode);

		rTrack.AppendKey(
		    uFrame,
		    Quaternion(oWorldFromNodeXform.rotation.x, oWorldFromNodeXform.rotation.y, oWorldFromNodeXform.rotation.z, oWorldFromNodeXform.rotation.w),
		    Vec3(oWorldFromNodeXform.translation.x, oWorldFromNodeXform.translation.y, oWorldFromNodeXform.translation.z),
		    Vec3(oWorldFromNodeXform.scale.x, oWorldFromNodeXform.scale.y, oWorldFromNodeXform.scale.z));
		uFrame += 1;
	}
}
else
{
	for (uint32_t iTranslation = 0; iTranslation < rNode.translation_keys.count; ++iTranslation)
	{
		ufbx_baked_vec3 oTranslation = rNode.translation_keys[iTranslation];
		rTrack._AppendTranslation(iTranslation, Vec3(oTranslation.value.x, oTranslation.value.y, oTranslation.value.z));
	}

	for (uint32_t iRotation = 0; iRotation < rNode.rotation_keys.count; ++iRotation)
	{
		ufbx_baked_quat oRotation = rNode.rotation_keys[iRotation];
		rTrack._AppendRotation(
		    iRotation, Quaternion(oRotation.value.x, oRotation.value.y, oRotation.value.z, oRotation.value.w));
	}

	for (uint32_t iScale = 0; iScale < rNode.scale_keys.count; ++iScale)
	{
		ufbx_baked_vec3 oScale = rNode.scale_keys[iScale];
		rTrack._AppendScale(iScale, Vec3(oScale.value.x, oScale.value.y, oScale.value.z));
	}
}
```

**Comment by bqqbarbhg** [comment]
Heya!

What you did for root bones looks roughly correct, unless there are other animated nodes below the root bone, which is not really common.

You should be able to evaluate the world transform of a given mode like this:

```c
ufbx_matrix evaluate_world_transform(ufbx_anim *anim, ufbx_node *node, double time)
{
    ufbx_matrix node_to_world = ufbx_identity_matrix;

    // Evaluate the local transforms of all parents at the time
    for (ufbx_node *n = node; n; n = n->parent) {
        ufbx_transform local_transform = ufbx_evaluate_transform(anim, n, time);
        ufbx_matrix node_to_parent = ufbx_transform_to_matrix(&local_transform);

        // Concatenate parent chain matrices: node_to_parent * (node_to_parent * (identity))
        node_to_world = ufbx_matrix_mul(&node_to_parent, &node_to_world);
    }

    return node_to_world;
}
```

The code is untested at the moment so it might need a bit of tweaking. It also doesn't handle advanced transform inherit modes. Might actually be something that I should add as a utility into ufbx for better parity with the SDK, thanks for the idea!

**Comment by Vincent-P** [comment]
Thanks, I ended up doing something similar :)
The code is way too complex due to up axis transformations...
Our new animation importer is 5 to 6 times faster than the old one using the official SDK (and can be multithreaded now!)

**Comment by bqqbarbhg** [comment]
Nice!

The nodes are sorted to make some internal operations be able to linearly process the nodes without recursion, as doing that you could crash the importer by doing a deep parent chain.

Good point on that though, I should really retain that information, added an issue for it #147. It might have been better to not mess with the default order but I didn't assume it to be significant in the files, and I think now it's a bit too late to change that, sorry!

You probably already do it but the `element_id` of the nodes should indicate the original order unless I'm mistaken.
