### ISSUE TITLE
Inconsistent quaternion rotations when baking animations

### ISSUE THREAD

**Issue by DanZaidan** [ufbx/ufbx#174]
Hello!!

First off, thanks a lot for the awesome work in ufbx, the best fbx importer I've used!! (And I've used quite a few).

I integrated ufbx on my engine almost a year ago and I'm currently adding support for animation-only fbx (by matching bone names with the skeleton fbx).

The animation loads correctly only in the first frame, and in the following frames it snaps to a wrong rotation value.
The quaternion values are, for example:
Frame 0: [-0.714351, -9.090e-5,  0.699709,  0.0104164]
Frame 1: [-0.714556, -8.785e-5, -0.699500, -0.0104164]

They are not negation of one another, so I'm not entirely sure what the problem is.
Several bones have this issue.

This is how the animation looks on frame 0:
![image](https://github.com/user-attachments/assets/b8dd0590-26e5-4642-ab08-dec1347f72f6)

This is how the animation looks on frame 1:
![image](https://github.com/user-attachments/assets/94b68ab4-0c96-458d-b715-3bb2d258fd95)

Here are the source fbx files:
[quat_issue.zip](https://github.com/user-attachments/files/18240072/quat_issue.zip)

Both files look correct in Maya, and the animation plays normally there.
This is why I'm assuming the problem is in the 'bake' procedure, when generating quaternions.

I have tried exporting the animation with different settings in Maya, and I'm only been able to change which the 'correct' keyframe from 0 to 1 and 3. I have also tried different ufbx_bake_opts, to no success.

Do you have any idea what the issue might be?

Thanks a lot!

**Comment by DanZaidan** [comment]
Updating ufbx fixed the issue!
I was using version 0.12.0, and upgrade to 0.15.1.

Happy 2025!!

**Comment by bqqbarbhg** [comment]
Heya, great to hear that it was fixed via an update :D

Are you perhaps using a left-handed coordinate system? I think I had some issues with baking rotations in that case in earlier versions.

**Comment by DanZaidan** [comment]
Indeed, I am!
The engine uses a left handed system: Z-Up, X-Forward, Y-right.

And this is the load_opts:

```
    // Right, Up, Front (Note: Front is _opposite_ from forward!)
    target_axis :: ufbx_coordinate_axes.{.NEGATIVE_Y, .POSITIVE_Z, .POSITIVE_X};
    target_unit_meters :: 1.0;
    
    opts := ufbx_load_opts.{ target_axes = target_axis,
                                           target_unit_meters = target_unit_meters,
                                           space_conversion = .MODIFY_GEOMETRY,
                                           handedness_conversion_axis = .Z };

**Comment by bqqbarbhg** [comment]
Neat! Axis conversion is one of the less tested areas of the library, so definitely let me know if you run into any other issues :D

**Comment by DanZaidan** [comment]
Will do!! Thanks a lot! 😁
