### ISSUE TITLE
Example looks convoluted, is there a simpler example?

### ISSUE THREAD

**Issue by torchesburn** [ufbx/ufbx#53]
Im using this with opengl glut.h and was wondering whether I could just extend the quick start lines in the readme.md to also using glut to render the image? Getting a blank screen on this.

```#include <GL/glut.h>
#include <ufbx.h>
#include<iostream>
#include <cstdio>

using namespace std;

// Initialize uFBX and load the FBX file
ufbx_load_opts opts = { 0 }; // Optional, pass NULL for defaults
ufbx_error error; // Optional, pass NULL if you don't care about errors
ufbx_scene *scene = ufbx_load_file("thing.FBX", &opts, &error);

// Display callback function
void display() {
    // Clear the buffer
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

  // Set the view matrix
  glLoadIdentity();
  gluLookAt(0, 0, 10, 0, 0, 0, 0, 1, 0);

  // Draw the model
  for (size_t i = 0; i < scene->nodes.count; i++) {
    ufbx_node *node = scene->nodes.data[i];
    if (node->is_root || !node->mesh) continue;

    ufbx_mesh *mesh = node->mesh;
    // cout << "Hello";  // prints Hello

    // Enable vertex arrays
    glEnableClientState(GL_VERTEX_ARRAY);
    glEnableClientState(GL_NORMAL_ARRAY);

    // Bind vertex and normal data
    // glVertexPointer(3, GL_FLOAT, 0, mesh->vertices.data);
    // glNormalPointer(GL_FLOAT, 0, mesh->fa.indices.data);

    // Draw the mesh
    glDrawElements(GL_TRIANGLES, mesh->faces.count * 3, GL_UNSIGNED_INT, mesh->faces.data);

    // Disable vertex arrays
    glDisableClientState(GL_VERTEX_ARRAY);
    glDisableClientState(GL_NORMAL_ARRAY);
  }

  // Swap buffers
  glutSwapBuffers();  
}

int main(int argc, char **argv) {

  try {

    // Initialize GLUT and create a window
  glutInit(&argc, argv);
  glutInitWindowSize(640, 480);
  glutCreateWindow("uFBX Test");

  if (!scene) {
      fprintf(stderr, "Failed to load: %s\n", error.description.data);
      exit(1);
  }

  // Set up OpenGL state and projection matrix
  glMatrixMode(GL_PROJECTION);
  glLoadIdentity();
  gluPerspective(45, 640.0 / 480.0, 0.1, 100);
  glMatrixMode(GL_MODELVIEW);
  glLoadIdentity();

  // Set up lighting
  GLfloat light_position[] = { 1.0, 1.0, 1.0, 0.0 };
  GLfloat light_ambient[] = { 0.2, 0.2, 0.2, 1.0 };
  GLfloat light_diffuse[] = { 0.8, 0.8, 0.8, 1.0 };
  // GLfloat light_specular[] = { 1
  // Set up materials
  GLfloat material_ambient[] = { 0.2, 0.2, 0.2, 1.0 };
  GLfloat material_diffuse[] = { 0.8, 0.8, 0.8, 1.0 };
  GLfloat material_specular[] = { 1.0, 1.0, 1.0, 1.0 };
  GLfloat material_shininess[] = { 50.0 };
  glMaterialfv(GL_FRONT, GL_AMBIENT, material_ambient);
  glMaterialfv(GL_FRONT, GL_DIFFUSE, material_diffuse);
  glMaterialfv(GL_FRONT, GL_SPECULAR, material_specular);
  glMaterialfv(GL_FRONT, GL_SHININESS, material_shininess);

  // Set up the display callback
  glutDisplayFunc(display);

  // Start the main loop
  glutMainLoop();
    
  }
   catch (runtime_error &e) {
    cout << "Error: " << e.what() << endl;
  }
  

  return 0;
}
```

**Comment by bqqbarbhg** [comment]
Hi! The documentation is still quite lacking and as you said the examples tend to be on the more complex end. I don't have time at the moment to draft one but I think I should add some sort of OpenGL example in the future. For now I recommend checking through the headers for documentation, especially [above `ufbx_mesh`](https://github.com/ufbx/ufbx/blob/542aefbd7a75d749124383ff512eee3491ededc0/ufbx.h#L986-L1033). Though even that explanation is a bit overly complex to how I'd want it to be these days.

Quick pointers:

- By default `ufbx_real` is defined as `double` and by extension `ufbx_vec3` etc as well, so you need to convert them to `float` for rendering
- If you have files that are not triangulated you need to either triangulate the geometry yourself or use `ufbx_triangulate_face()`
- If you need any other vertex attributes than the positions you can't rely on the indices, but need to use `ufbx_get_vertex_vec3()` for each index
- You generally need to account for node transforms, you can use `ufbx_node.geometry_to_world` as the model transformation if you don't care about animation.

I know it's kind of buried within features but the viewer example illustrates how to handle this, this snippet handles triangulation and converting `ufbx_vec3` to a single precision `float` for rendering. You can ignore the skinning part and `f_vertex_index`.

https://github.com/ufbx/ufbx/blob/542aefbd7a75d749124383ff512eee3491ededc0/examples/viewer/viewer.c?ts=4#L408-L438

For more optimal rendering these vertices are compacted to use an index buffer below, but that is optional if you don't need to use indexed rendering. Again, the skinning part is optional.

https://github.com/ufbx/ufbx/blob/542aefbd7a75d749124383ff512eee3491ededc0/examples/viewer/viewer.c?ts=4#L440-L459

**Comment by torchesburn** [comment]
Thats I will try to use these two functions and see if I can make it work with opengl glut
