### ISSUE TITLE
a mocap.market data can't load.

### ISSUE THREAD

**Issue by piroshikin** [ufbx/ufbx#65]
I always use ufbx conveniently. Thank you!
When I load an fbx file downloaded from mocap.market,
it fails in ufbxi_read_mesh() in the branch if(n->name == ufbxi_LayerElementSmoothing),
where there is ufbxi_check(ufbxi_read_truncated_array(uc, &mesh->edge_smoothing.data, &mesh->edge_smoothing.count, n, ufbxi_Smoothing, ‘b’, mesh->num_edges)); 
and the process returns. As far as I can see, 
it is looking for “Smoothing” in n(node) passed as an argument by ufbx_find_child, 
but the actual data contains “Version”,“Name”,“MappingInformationType”,“ReferenceInformationType”, 
and Smoothing is not found, so the process seems to end.
Do you know any solutions or ways to investigate this?

**Comment by bqqbarbhg** [comment]
Thanks for the issue! I was able to reproduce it myself and looks like you're correct in your assessment, for some reason the `LayerElementSmoothing` block is missing the smoothing data. I'll do a proper fix and test case soon, but if you need an urgent hotfix you can replace the following line in `ufbxi_read_truncated_array()`:

```diff
- ufbxi_check(arr);
+ if (!arr) return 1;
```

This should make the file load and ignore the error, I'll probably change it into a warning in the proper fix.

**Comment by piroshikin** [comment]
to bqqbarbhg
Thank you for your response.
Although there is still an issue, the file has been loaded!
Thank you.
