### ISSUE TITLE
How to get index data in mesh?

### ISSUE THREAD

**Issue by mingxingren** [ufbx/ufbx#66]

**Comment by bqqbarbhg** [comment]
Heya! FBX files don't have index data in a way that graphics APIs would expect it, but each attribute has its own internal indices. You shouldn't rely on those however and just treat the vertices as flat arrays accessed via `ufbx_get_vertex_vec3(..., index)` where `index` goes from `0` to `mesh.num_indices - 1`. Faces are defined as ranges of these indices, so to create an index buffer suitable for graphics APIs you need to triangulate those as well.

 See https://ufbx.github.io/guide/basics/geometry for more information, sorry that the docs are not linked by default, I want to clean them up before I put them up in the public!

**Comment by mingxingren** [comment]
Ok, Thanks for you replay
