### ISSUE TITLE
How to read bone information and how to combine with vertex point

### ISSUE THREAD

**Issue by mingxingren** [ufbx/ufbx#67]
Hello author!
I read vertex point information from ufbx_mesh::vertex_position.  
How do I read bone index and bone weight? And  How to map How to map bone weight to vertex points?

The following is my read vertex point method:

`
    // Get mesh bones
    std::vector<BoneInfo> bones;

    if (node->mesh->skin_deformers.count > 0)
    {
        ufbx_skin_deformer *skin = node->mesh->skin_deformers.data[0];
        for (size_t i = 0; i < skin->clusters.count; i++)
        {
            ufbx_skin_cluster *cluster = skin->clusters.data[i];

            BoneInfo bone_info;
            uint32_t bone_index = cluster->bone_node->typed_id;
            bone_info.name = std::string(cluster->bone_node->name.data, cluster->bone_node->name.length);

            ufbx_matrix geometry_to_bone = cluster->geometry_to_bone;
            glm::mat4 mesh_point_to_bone_space = GetGlmMatrix(geometry_to_bone);
            bones.push_back(bone_info);
        }
    }
    mesh_data.bones = std::move(bones);

    // 获取网格顶点
    std::vector<VertexData> vertex_data_array;

    ufbx_skin_deformer *skin = node->mesh->skin_deformers.data[0];

    uint32_t vertex_point_count = node->mesh->num_indices;
    node->mesh->num_vertices;
    for (uint32_t i = 0; i < vertex_point_count; i++)
    {
        VertexData vertex_data;

        ufbx_vec3 tmp_point = ufbx_get_vertex_vec3(&node->mesh->vertex_position, i);
        vertex_data.vertex_pos.x = tmp_point.x;
        vertex_data.vertex_pos.y = tmp_point.y;
        vertex_data.vertex_pos.z = tmp_point.z;
        
        ufbx_vec3 tmp_normal = ufbx_get_vertex_vec3(&node->mesh->vertex_normal, i);
        vertex_data.normal.x = tmp_normal.x;
        vertex_data.normal.y = tmp_normal.y;
        vertex_data.normal.z = tmp_normal.z;
        
        ufbx_vec2 tmp_uv_pos = ufbx_get_vertex_vec2(&node->mesh->vertex_uv, i);
        vertex_data.uv_pos.x = tmp_uv_pos.x;
        vertex_data.uv_pos.y = tmp_uv_pos.y;
        // fmt::print("{} vertex point ({}, {}, {}) \n", i, tmp_point.x,  tmp_point.y,  tmp_point.z);
    }

    // 获取索引顶点
    uint32_t faces_count = node->mesh->num_faces;
    fmt::print("face count: {} \n", faces_count);

    uint32_t index_reciever[128];
    for (uint32_t i = 0; i < faces_count; i++)
    {
        ufbx_face& face_index = node->mesh->faces[i];
        if (ufbx_get_triangulate_face_num_indices(face_index) > 0)
        {
            uint32_t triangulate_count = ufbx_triangulate_face(index_reciever, 128, node->mesh, face_index);
            for (uint32_t j = 0; j < triangulate_count; j++)
            {
                for (uint32_t k = 0; k < 3; k++) {
                    uint32_t index = index_reciever[j * 3 + k];
                    mesh_data.indexs.push_back(index);
                }
            }
        }
    }

    // this code aime to Get vertex point's bone weight and index, But getting the number of bones is far less than reading the number of vertices
    int test_i = 0;
    for (size_t vi = 0; vi < node->mesh->num_vertices; vi++) {
        size_t num_weights = 0;
        float total_weight = 0.0f;
        float weights[4] = { 0.0f };
        uint8_t clusters[4] = { 0 };

        ufbx_skin_vertex vertex_weights = skin->vertices.data[vi];
        for (size_t wi = 0; wi < vertex_weights.num_weights; wi++) {
            if (num_weights >= 4) 
                break;
            ufbx_skin_weight weight = skin->weights.data[vertex_weights.weight_begin + wi];

            if (weight.cluster_index < 100) {
                total_weight += (float)weight.weight;
                clusters[num_weights] = (uint8_t)weight.cluster_index;
                weights[num_weights] = (float)weight.weight;
                num_weights++;
            }

            test_i++;
        }
    }
}`

**Comment by bqqbarbhg** [comment]
Hi, yea this is one of the more confusing parts of the API, sorry about that! You can map indices to vertices (up to `ufbx_mesh.num_vertices`) using `ufbx_mesh.vertex_indices[]` for each *index* (up to `ufbx_mesh.num_indices`). In practice you can either duplicate work and run the skinning cluster/weight loop for every index like this:

```cpp
for (size_t ix = 0; ix < node->mesh->num_indices; ix++) {
    size_t vi = node->mesh->vertex_indices[ix];
    size_t num_weights = 0;
    float weights[4] = { 0.0f };
    uint8_t clusters[4] = { 0 };
    // ...

    // Write the skinning data to the vertices
    vertex_data_array[ix].weights = weights; // would need memcpy() or something due to array but you know
    vertex_data_array[ix].clusters = clusters;
}
```

Another option is to precompute the skinning bone indices/weights before going over each index as is done in the example, note that we have a temporary array up to `num_vertices`

https://github.com/ufbx/ufbx/blob/30f035bbe5ecd90860392825eb586b5110400aa8/examples/viewer/viewer.c#L296

that we later write to in the loop that computes the skinning values

https://github.com/ufbx/ufbx/blob/30f035bbe5ecd90860392825eb586b5110400aa8/examples/viewer/viewer.c#L367

and then when we form the geometry we copy the per-vertex data for each index in the loop below:

https://github.com/ufbx/ufbx/blob/30f035bbe5ecd90860392825eb586b5110400aa8/examples/viewer/viewer.c#L430-L434

**Comment by mingxingren** [comment]
Ok, I know how to do with your help. Thank you very much!!!
