### ISSUE TITLE
How to use ufbx_blend_shape?

### ISSUE THREAD

**Issue by mingxingren** [ufbx/ufbx#68]
Hello, 
I read offset point from ufbx_blend_shape.  I think ufbx_blend_shape::offset_vertices is the index into the ufbx_mesh::vertex_position array. And  ufbx_blend_shape::position_offsets  ufbx_blend_shape::normal_offsets are offset of the point. But When adding ufbx_mesh::vertex_position and ufbx_blend_shape::position_offsets, it did not get the correct result.

What did i do wrong?

**Comment by mingxingren** [comment]
This is Model which I use. 
https://github.com/SunnyViewTech/DollarsLiveLinkFace/raw/main/Assets/SampleHead.fbx

**Comment by bqqbarbhg** [comment]
Heya, sorry for the delay! You can consider each blend shape as a subset of vertices of the mesh so doing something like (in pseudo-C, you would need conversions from ufbx vectors to custom ones etc):

```c
ufbx_mesh *mesh;
ufbx_blend_shape *shape;
Vector3 positions[];
float some_weight; // Add shape to mesh positions by this weight

for (uint32_t i = 0; i < mesh->num_vertices; i++) {
    positions[i] = mesh->vertices.data[i];
}

for (uint32_t i = 0; i < shape->num_offsets; i++) {
    uint32_t vertex_index = shape->offset_vertices.data[i];
    Vector3 offset = shape->position_offsets.data[i];
    positions[i] += offset * some_weight;
}
```

However if you want to store the blend offsets per vertex or index you can use `ufbx_get_blend_shape_vertex_offset()` to get an offset per vertex:

```c
struct Vertex {
	Vector3 position;
	Vector2 uv;
	Vector3 blend_offset;
};

ufbx_mesh *mesh;
ufbx_blend_shape *shape;
Vertex vertices[];

for (uint32_t ix = 0; ix < mesh->num_indices; ix++) {
	vertices[ix].position = ufbx_get_vertex_vec3(&mesh->vertex_position, ix);
	vertices[ix].uv = ufbx_get_vertex_vec2(&mesh->vertex_uv, ix);

	uint32_t vertex_ix = mesh->vertex_indices.data[ix];
	ufbx_vec3 blend_offset = ufbx_get_blend_shape_vertex_offset(shape, vertex_ix);
	vertices[ix].blend_offset = blend_offset;
}
```

**Comment by mingxingren** [comment]
Thanks for your replay!
I tried your second suggestion and it works fine.
I have a question.  it is I blend vertex point and blend offset point one by one.  I want to blend offset points which have real changes. instead of calculate all  points. 

Does the FBX model only record which points actually changed?

looking forward to your reply! thanks!

**Comment by bqqbarbhg** [comment]
Hi, sorry for the late response again. FBX does indeed store the actual changed points, which is why `ufbx_blend_shape.offset_vertices[]` contains a list of vertices that the blend shape modifies. This is a little tricky as it's defined in the terms of _vertices_ and not _indices_, ie. one blend shape offset can affect the corners of multiple polygons via the same vertex index. There's currently no convenient way of getting all the indices for a given vertex index, you could do something like this (quite inefficient and in C++..):

```cpp
ufbx_mesh *mesh;
ufbx_blend_shape *shape;

// All indices referring to a given vertex
std::vector<std::vector<uint32_t>> vertex_indices;
vertex_indices.resize(mesh->num_vertices);

for (uint32_t ix = 0; ix < mesh->num_indices; ix++) {
    uint32_t vertex_ix = mesh->vertex_indices[ix];
    vertex_indices[vertex_ix].push_back(ix);
}

// Now for each blend shape offset you can get indices as such
for (uint32_t i = 0; i < shape->num_offsets; i++) {
    uint32_t vertex_ix = shape->offset_vertices[i];
    ufbx_vec3 pos_offset = shape->offset_positions[i];
    // `pos_offset` applies to all indices vertex_indices[vertex_ix]
}
```

**Comment by mingxingren** [comment]
Ok, Thank you very much for your reply
