### ISSUE TITLE
Shadowing of variables

### ISSUE THREAD

**Issue by fire** [ufbx/ufbx#71]
```
In file included from modules/fbx/gltf_document.cpp:74:
modules/fbx/thirdparty/ufbx/ufbx.h: In constructor 'ufbx_ref<T>::ufbx_ref(T*)':
Error: modules/fbx/thirdparty/ufbx/ufbx.h:4654:37: error: declaration of 'ptr' shadows a member of 'ufbx_ref<T>' [-Werror=shadow]
 4654 |  explicit ufbx_ref(T *ptr) noexcept : ptr(ptr) { }
      |                                     ^
modules/fbx/thirdparty/ufbx/ufbx.h:4690:5: note: shadowed declaration is here
 4690 |  T *ptr;
      |     ^~~
```

Thanks to your tweets I was trying out ufbx.

![image](https://github.com/ufbx/ufbx/assets/32321/647e58ef-2a82-480e-add3-ebe8065ca504)

![image](https://github.com/ufbx/ufbx/assets/32321/25444dee-4f61-4ec3-9881-f2bc600d9041)

**Comment by bqqbarbhg** [comment]
Thanks for the issue, got it reproduced! Should be fixed along with a bunch of other advanced warnings in #72 (tagged as version v0.5.1).

**Comment by fire** [comment]
I'll check back later, but I'll close for now.
