### ISSUE TITLE
Fix/test handedness conversion

### ISSUE THREAD

**Issue by bqqbarbhg** [ufbx/ufbx#84]
Currently if using root transforms handedness scales root node which is not great. If using adjust transforms the handling is likely broken.

**Comment by fire** [comment]
Does this break adjust geometry?

**Comment by bqqbarbhg** [comment]
This is actually the issue that spawned adjust geometry, which was an offshoot from handedness conversion, which requires modifying geometry to avoid negative scaling.

The feature itself is starting to get mature and well tested now though.
